--stock_id table
CREATE TABLE cmsy.stock_id (
	stock_id_area varchar primary key,
	stock_id varchar,
	stock_num int4,
	taxon_key int4,
	scientific_name varchar,
	common_name varchar,
	functional_group varchar,
	marine_layer_id int4,
	marine_layer varchar,
	stradling_or_not bool,
	area_id int4,
	area varchar,
	stock_status varchar,
	date_modified int4,
	ref_id int4,
	date_entered int4,
	"comments" text
);

--relative biomass table
create table cmsy.rel_biom (
	rel_biom_id int4 primary key,
	rel_biom_meta_id int4,
	stock_id varchar,
	"year" int4,
	value float8
);

--relative biomass meta data table
create table cmsy.rel_biom_meta (
	rel_biom_meta_id int4 primary key,
	stock_id int4,
	data_type varchar,
	units varchar,
	year_start int4,
	year_end int4,
	years_missing int4,
	region_description varchar,
	gear_type_id int4,
	gear_type varchar,
	ref_id int4
);

--relative reference table
create table cmsy.reference (
	ref_id int4 primary key,
	author varchar,
	"year" int4,
	title text,
	"source" varchar,
	short_citation varchar,
	journal int4,
	"language" varchar,
	ref_type varchar,
	author_address text,
	pdf_file varchar,
	pdf_url text
);
	
--relative ref_content table
create table cmsy.ref_content (
	ref_content_id int4 primary key,
	ref_id int4,
	stock_id int4,
	page varchar,
	sci_name varchar,
	info_format varchar,
	info_drawn varchar
);

--priors table
create table cmsy.priors (
	stock_id int4,
	min_of_year int4,
	max_of_year int4,
	start_year int4,
	end_year int4,
	main_ref_id int4 primary key,
	max_catch float8,
	last_catch float8,
	b_bmsy_last_5_years float8,
	flim float8,
	fpa float8,
	blim float8,
	bpa float8,
	fmsy float8,
	msy_btrigger float8,
	b40 float8,
	m float8,
	fofl float8,
	last_f float8,
	resilience varchar,
	resilience_expert int4,
	r_low float8,
	r_hi float8,
	r_expert int4,
	r_modeled int4,
	stb_low float8,
	stb_hi float8,
	stb_expert int4,
	stb_modeled int4,
	int_year int4,
	intb_low float8,
	intb_hi float8,
	int_expert int4,
	int_modeled int4,
	endb_low float8,
	endb_hi float8,
	endb_expert int4,
	endb_modeled int4,
	q_start int4,
	q_end int4,
	q_expert int4,
	q_modeled int4,
	e_creep int4,
	btype varchar,
	force_fmsy varchar,
	msy_bsm float8,
	msy_bsm_lcl float8,
	msy_bsm_ucl float8,
	r_bsm float8,
	r_bsm_lcl float8,
	r_bsm_ucl float8,
	k_bsm float8,
	k_bsm_lcl float8,
	k_bsm_ucl float8,
	q_bsm float8,
	q_bsm_lcl float8,
	q_bsm_ucl float8,
	rel_b_bsm float8,
	rel_b_bsm_lcl float8,
	rel_b_bsm_ucl float8,
	rel_f_bsm float8,
	r_cmsy float8,
	r_cmsy_lcl float8,
	r_cmsy_ucl float8,
	k_cmsy float8,
	k_cmsy_lcl float8,
	k_cmsy_ucl float8,
	msy_cmsy float8,
	msy_cmsy_lcl float8,
	msy_cmsy_ucl float8,
	rel_b_cmsy float8,
	rel_b_cmsy_lcl float8,
	rel_b_cmsy_ucl float8,
	rel_f_cmsy float8,
	f_msy float8,
	f_msy_lcl float8,
	f_msy_ucl float8,
	curf_msy float8,
	curf_msy_lcl float8,
	curf_msy_ucl float8,
	msy float8,
	msy_lcl float8,
	msy_ucl float8,
	bmsy float8,
	bmsy_lcl float8,
	bmsy_ucl float8,
	b float8,
	b_lcl float8,
	b_ucl float8,
	b_bmsy float8,
	b_bmsy_lcl float8,
	b_bmsy_ucl float8,
	f float8,
	f_lcl float8,
	f_ucl float8,
	f_fmsy float8,
	f_fmsy_lcl float8,
	f_fmsy_ucl float8,
	sel_b float8,
	sel_b_bmsy float8,
	sel_f float8,
	sel_f_fmsy float8
);
