CREATE OR REPLACE FUNCTION get_current_time_of_day()
RETURNS timestamp AS
$BODY$
BEGIN
	RETURN TO_TIMESTAMP(timeofday(), 'Dy Mon DD HH24:MI:SS.US YYYY');
END;
$BODY$
LANGUAGE plpgsql
CALLED ON NULL INPUT
VOLATILE
EXTERNAL SECURITY INVOKER;

